---

driver:
  name: vagrant

provisioner:
  ansible_verbose: true
  ansible_verbosity: 2
  hosts: test-kitchen
  name: ansible_playbook
  require_chef_for_busser: false
  require_ruby_for_busser: true

platforms:
- name: ubuntu-14.04

suites:
  - name: default

# Fix for: https://github.com/neillturner/kitchen-ansible/issues/66
verifier:
  ruby_bindir: '/usr/bin'

