---

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git

- name: Create Fabio directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ fabio_download_dir }}"
    - "{{ fabio_directories_config }}"
    - "{{ fabio_directories_install }}"
    - "{{ fabio_directories_log }}"
  when: fabio_create_directories

- include: install_src.yml
  when: fabio_install_from_source

- include: install_binary.yml
  when: not fabio_install_from_source

- name: Create fabio user
  include: user.yml
  when: fabio_create_user

- name: Install Fabio Upstart service
  template:
    dest: /etc/init/fabio.conf
    mode: 0755
    src: fabio.service.upstart.j2
  when: ansible_service_mgr == "upstart"

- name: Install Fabio Systemd service
  template:
    dest: /etc/systemd/system/fabio.service
    mode: 0755
    src: fabio.service.systemd.j2
  when: ansible_service_mgr == "systemd"

- name: Enable Fabio service
  service:
    enabled: yes
    name: fabio
  when: fabio_manage_service
